
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context";
import axios from "axios";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  axios.defaults.withCredentials = true;
  // Change base URL for Axios requests
  axios.defaults.baseURL = process.env.NODE_ENV === 'production' ? 'https://localhost:3000/api' : 'http://localhost:3000/api';

  return (
    <>
      <html lang="en" style={{ height: "100%" }}>
        <UserProvider><body style={{ height: "100%" }}>
          {children}
        </body></UserProvider>
      </html>
    </>
  );
}
